export const LOAD_DONATION_CONTACT_CATEGORY_REQUEST =
  'app/container/DonationContact/LOAD_DONATION_CONTACT_CATEGORY_REQUEST';
export const LOAD_DONATION_CONTACT_CATEGORY_SUCCESS =
  'app/container/DonationContact/LOAD_DONATION_CONTACT_CATEGORY_SUCCESS';
export const LOAD_DONATION_CONTACT_CATEGORY_FAILURE =
  'app/container/DonationContact/LOAD_DONATION_CONTACT_CATEGORY_FAILURE';

export const CLEAR_MESSAGE = 'app/containers/HowYouCanHelp/CLEAR_MESSAGE';
