// export const GET_REPORT_LISTING_REQUEST = 'PCSC/Report/GET_REPORT_LISTING_REQUEST';
// export const GET_REPORT_LISTING_SUCCESS = 'PCSC/Report/GET_REPORT_LISTING_SUCCESS';
// export const GET_REPORT_LISTING_FAILURE = 'PCSC/Report/GET_REPORT_LISTING_FAILURE';




export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
