/*
 *
 * ViewPractice constants
 *
 */

export const SAVE_ANSWER_REQUEST = 'app/ViewPractice/SAVE_ANSWER_REQUEST';
export const SAVE_ANSWER_SUCCESS = 'app/ViewPractice/SAVE_ANSWER_SUCCESS';
export const SAVE_ANSWER_FAILURE = 'app/ViewPractice/SAVE_ANSWER_FAILURE';

export const DEFAULT_ACTION_REQUEST = 'app/ViewPractice/DEFAULT_ACTION_REQUEST';
export const DEFAULT_ACTION_SUCCESS = 'app/ViewPractice/DEFAULT_ACTION_SUCCESS';
export const DEFAULT_ACTION_FAILURE = 'app/ViewPractice/DEFAULT_ACTION_FAILURE';

export const LOAD_ALL_QUESTIONNAIRE_REQUEST =
  'app/ViewPractice/LOAD_ALL_QUESTIONNAIRE_REQUEST';
export const LOAD_ALL_QUESTIONNAIRE_SUCCESS =
  'app/ViewPractice/LOAD_ALL_QUESTIONNAIRE_SUCCESS';
export const LOAD_ALL_QUESTIONNAIRE_FAILURE =
  'app/ViewPractice/LOAD_ALL_QUESTIONNAIRE_FAILURE';

export const FAVORITE_QUESTION_REQUEST =
  'app/ViewPractice/FAVORITE_QUESTION_REQUEST';
export const FAVORITE_QUESTION_SUCCESS =
  'app/ViewPractice/FAVORITE_QUESTION_SUCCESS';
export const FAVORITE_QUESTION_FAILURE =
  'app/ViewPractice/FAVORITE_QUESTION_FAILURE';

export const UNFAVORITE_QUESTION_REQUEST =
  'app/ViewPractice/UNFAVORITE_QUESTION_REQUEST';
export const UNFAVORITE_QUESTION_SUCCESS =
  'app/ViewPractice/UNFAVORITE_QUESTION_SUCCESS';
export const UNFAVORITE_QUESTION_FAILURE =
  'app/ViewPractice/UNFAVORITE_QUESTION_FAILURE';

export const LOAD_ALL_FAVORITE_QUESTIONNAIRE_REQUEST =
  'app/ViewPractice/LOAD_ALL_FAVORITE_QUESTIONNAIRE_REQUEST';
export const LOAD_ALL_FAVORITE_QUESTIONNAIRE_SUCCESS =
  'app/ViewPractice/LOAD_ALL_FAVORITE_QUESTIONNAIRE_SUCCESS';
export const LOAD_ALL_FAVORITE_QUESTIONNAIRE_FAILURE =
  'app/ViewPractice/LOAD_ALL_FAVORITE_QUESTIONNAIRE_FAILURE';

export const LOAD_EXAM_BY_ID_REQUEST =
  'app/ViewPractice/LOAD_EXAM_BY_ID_REQUEST';
export const LOAD_EXAM_BY_ID_SUCCESS =
  'app/ViewPractice/LOAD_EXAM_BY_ID_SUCCESS';
export const LOAD_EXAM_BY_ID_FAILURE =
  'app/ViewPractice/LOAD_EXAM_BY_ID_FAILURE';

export const LOAD_TRIAL_QUESTIONNAIRE_REQUEST =
  'app/ViewPractice/LOAD_TRIAL_QUESTIONNAIRE_REQUEST';
export const LOAD_TRIAL_QUESTIONNAIRE_SUCCESS =
  'app/ViewPractice/LOAD_TRIAL_QUESTIONNAIRE_SUCCESS';
export const LOAD_TRIAL_QUESTIONNAIRE_FAILURE =
  'app/ViewPractice/LOAD_TRIAL_QUESTIONNAIRE_FAILURE';

export const POST_RESULT_REQUEST = 'app/ViewPractice/POST_RESULT_REQUEST';
export const POST_RESULT_SUCCESS = 'app/ViewPractice/POST_RESULT_SUCCESS';
export const POST_RESULT_FAILURE = 'app/ViewPractice/POST_RESULT_FAILURE';

export const POST_QUESTION_SCORE_REQUEST =
  'app/ViewPractice/POST_QUESTION_SCORE_REQUEST';
export const POST_QUESTION_SCORE_SUCCESS =
  'app/ViewPractice/POST_QUESTION_SCORE_SUCCESS';
export const POST_QUESTION_SCORE_FAILURE =
  'app/ViewPractice/POST_QUESTION_SCORE_FAILURE';

export const CLEAR_MESSAGE = 'app/ViewPractice/CLEAR_MESSAGE';
