/*
 *
 * Team Member constants
 *
 */

export const LOAD_ALL_INTERVIEW_REQUEST = 'app/Interview/LOAD_ALL_INTERVIEW_REQUEST';
export const LOAD_ALL_INTERVIEW_SUCCESS = 'app/Interview/LOAD_ALL_INTERVIEW_SUCCESS';
export const LOAD_ALL_INTERVIEW_FAILURE = 'app/Interview/LOAD_ALL_INTERVIEW_FAILURE';

export const LOAD_INTERVIEW_BY_ID_REQUEST = 'app/Interview/LOAD_INTERVIEW_BY_ID_REQUEST';
export const LOAD_INTERVIEW_BY_ID_SUCCESS = 'app/Interview/LOAD_INTERVIEW_BY_ID_SUCCESS';
export const LOAD_INTERVIEW_BY_ID_FAILURE = 'app/Interview/LOAD_INTERVIEW_BY_ID_FAILURE';
