export const LOAD_DONATION_DROPOFF_REQUEST = "app/containers/DropOff/LOAD_PARTENERSHIP_REQUEST";
export const LOAD_DONATION_DROPOFF_SUCCESS = "app/containers/DropOff/LOAD_DONATION_DROPOFF_SUCCESS";
export const LOAD_DONATION_DROPOFF_FAILURE = "app/containers/DropOff/LOAD_DONATION_DROPOFF_FAILURE";

export const LOAD_DONATION_DROPOFF_BY_SLUG_REQUEST = "app/containers/DropOff/LOAD_DONATION_DROPOFF_BY_SLUG_REQUEST";
export const LOAD_DONATION_DROPOFF_BY_SLUG_SUCCESS = "app/containers/DropOff/LOAD_DONATION_DROPOFF_BY_SLUG_SUCCESS";
export const LOAD_DONATION_DROPOFF_BY_SLUG_FAILURE = "app/containers/DropOff/LOAD_DONATION_DROPOFF_BY_SLUG_FAILURE";

