export const LOAD_TEAM_MEMBER_REQUEST = 'app/TeamMember/LOAD_TEAM_MEMBER_REQUEST';
export const LOAD_TEAM_MEMBER_SUCCESS = 'app/TeamMember/LOAD_TEAM_MEMBER_SUCCESS';
export const LOAD_TEAM_MEMBER_FAILURE = 'app/TeamMember/LOAD_TEAM_MEMBER_FAILURE';

export const LOAD_TEAM_MEMBER_BY_SLUG_REQUEST =
  'app/TeamMember/LOAD_TEAM_MEMBER_BY_SLUG_REQUEST';
export const LOAD_TEAM_MEMBER_BY_SLUG_SUCCESS =
  'app/TeamMember/LOAD_TEAM_MEMBER_BY_SLUG_SUCCESS';
export const LOAD_TEAM_MEMBER_BY_SLUG_FAILURE =
  'app/TeamMember/LOAD_TEAM_MEMBER_BY_SLUG_FAILURE';
