export const RESEND_CONFIRMATION_REQUEST = 'XcelTrip/UserDashboard/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'XcelTrip/UserDashboard/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'XcelTrip/UserDashboard/RESEND_CONFIRMATION_FAILURE';


export const GET_CART_ITEMS_NUMBER_REQUEST = 'XcelTrip/UserDashboard/GET_CART_ITEMS_NUMBER_REQUEST';
export const GET_CART_ITEMS_NUMBER_SUCCESS = 'XcelTrip/UserDashboard/GET_CART_ITEMS_NUMBER_SUCCESS';
export const GET_CART_ITEMS_NUMBER_FAILURE = 'XcelTrip/UserDashboard/GET_CART_ITEMS_NUMBER_FAILURE';

export const CLEAR_STATE = 'XcelTrip/UserDashboard/CLEAR_STATE';
