/*
 *
 * Login constants
 *
 */

export const CHECK_CAPTCHA_REQUEST = "PCSC/Login/CHECK_CAPTCHA_REQUEST";
export const CHECK_CAPTCHA_SUCCESS = "PCSC/Login/CHECK_CAPTCHA_SUCCESS";
export const CHECK_CAPTCHA_FAILURE = "PCSC/Login/CHECK_CAPTCHA_FAILURE";

export const LOGIN_REQUEST = "PCSC/Login/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "PCSC/Login/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "PCSC/Login/LOGIN_FAILURE";

export const PRIVATE_KEY_REQUEST = "PCSC/Login/PRIVATE_KEY_REQUEST";
export const PRIVATE_KEY_SUCCESS = "PCSC/Login/PRIVATE_KEY_SUCCESS";
export const PRIVATE_KEY_FAILURE = "PCSC/Login/PRIVATE_KEY_FAILURE";

export const LOGIN_BY_TOKEN_REQUEST = "PCSC/Login/LOGIN_BY_TOKEN_REQUEST";
export const LOGIN_BY_TOKEN_SUCCESS = "PCSC/Login/LOGIN_BY_TOKEN_SUCCESS";
export const LOGIN_BY_TOKEN_FAILURE = "PCSC/Login/LOGIN_BY_TOKEN_FAILURE";

export const LOGIN_CLEAR_STATE = "PCSC/Login/LOGIN_CLEAR_STATE";
export const LOGIN_CLEAR_MESSAGES = "PCSC/Login/LOGIN_CLEAR_MESSAGES";

export const LOGOUT_REQUEST = "PCSC/Login/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "PCSC/Login/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "PCSC/Login/LOGOUT_FAILURE";

export const UPDATE_USER_INFO = "PCSC/Login/UPDATE_USER_INFO";

export const RESEND_CONFIRMATION_REQUEST = 'PCSC/Login/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'PCSC/Login/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'PCSC/Login/RESEND_CONFIRMATION_FAILURE';

export const LINK_FACEBOOK_REQUEST = "PCSC/Login/LINK_FACEBOOK_REQUEST";
export const LINK_FACEBOOK_SUCCESS = "PCSC/Login/LINK_FACEBOOK_SUCCESS";
export const LINK_FACEBOOK_FAILURE = "PCSC/Login/LINK_FACEBOOK_FAILURE";

export const LINK_GOOGLE_REQUEST = "PCSC/Login/LINK_GOOGLE_REQUEST";
export const LINK_GOOGLE_SUCCESS = "PCSC/Login/LINK_GOOGLE_SUCCESS";
export const LINK_GOOGLE_FAILURE = "PCSC/Login/LINK_GOOGLE_FAILURE";

export const SET_EMAIL = 'PCSC/Login/SET_EMAIL';
