export const GET_REPORT_LISTING_REQUEST = 'app/ReferShare/GET_REPORT_LISTING_REQUEST';
export const GET_REPORT_LISTING_SUCCESS = 'app/ReferShare/GET_REPORT_LISTING_SUCCESS';
export const GET_REPORT_LISTING_FAILURE = 'app/ReferShare/GET_REPORT_LISTING_FAILURE';


export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
