export const CHANGE_REFERRAL_REQUEST = 'app/ReferShare/CHANGE_REFERRAL_REQUEST';
export const CHANGE_REFERRAL_SUCCESS = 'app/ReferShare/CHANGE_REFERRAL_SUCCESS';
export const CHANGE_REFERRAL_FAILURE = 'app/ReferShare/CHANGE_REFERRAL_FAILURE';

export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
