export const GET_GRAPH_REQUEST = 'PCSC/ReportDetail/GET_GRAPH_REQUEST';
export const GET_GRAPH_SUCCESS = 'PCSC/ReportDetail/GET_GRAPH_SUCCESS';
export const GET_GRAPH_FAILURE = 'PCSC/ReportDetail/GET_GRAPH_FAILURE';

export const DOWNLOAD_REPORT_REQUEST = 'PCSC/ReportDetail/DOWNLOAD_REPORT_REQUEST';
export const DOWNLOAD_REPORT_SUCCESS = 'PCSC/ReportDetail/DOWNLOAD_REPORT_SUCCESS';
export const DOWNLOAD_REPORT_FAILURE = 'PCSC/ReportDetail/DOWNLOAD_REPORT_FAILURE';


export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
