export const RESEND_CONFIRMATION_REQUEST = 'PCSC/UserDashboard/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'PCSC/UserDashboard/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'PCSC/UserDashboard/RESEND_CONFIRMATION_FAILURE';

export const CLEAR_STATE = 'PCSC/UserDashboard/CLEAR_STATE';
