export const GET_CONSULTANTS_REQUEST = 'PCSC/HomePage/RESEND_CONFIRMATION_REQUEST';
export const GET_CONSULTANTS_SUCCESS = 'PCSC/HomePage/RESEND_CONFIRMATION_SUCCESS';
export const GET_CONSULTANTS_FAILURE = 'PCSC/HomePage/RESEND_CONFIRMATION_FAILURE';

export const GET_PRODUCTS_REQUEST = 'PCSC/HomePage/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'PCSC/HomePage/GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'PCSC/HomePage/GET_PRODUCTS_FAILURE';

export const GET_PRODUCTS_DETAILS_REQUEST = 'PCSC/HomePage/GET_PRODUCTS_DETAILS_REQUEST';
export const GET_PRODUCTS_DETAILS_SUCCESS = 'PCSC/HomePage/GET_PRODUCTS_DETAILS_SUCCESS';
export const GET_PRODUCTS_DETAILS_FAILURE = 'PCSC/HomePage/GET_PRODUCTS_FAILURE';

export const CLEAR_STATE = 'PCSC/HomePage/CLEAR_STATE';

